[package]
name = "editor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
r3d = { path = ".." }

lazy_static = { version = "1" }
pollster = { version = "0.3" }
thiserror = { version = "1" }
